
services:
  fishback:
    container_name: fishback
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


  fishfront:
    container_name: fishfront
    build: .
    ports:
      - "3000:3000"


